# Generated by Django 3.2.3 on 2021-09-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAccountManager',
        ),
    ]
