# Generated by Django 3.1 on 2021-09-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210919_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofle',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/default-user.png', upload_to='userprofile'),
        ),
    ]
